### ISSUE TITLE
where plugin searches for icon aliases

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_tab_icons#1]
https://github.com/halfbrained/cuda_tab_icons-1

плагин ищет некие иконки по алиасам. а для какого набора иконок это? для vscode 16x16?

**Comment by Alexey-T** [comment]
а сама эта тема то где? может ее включить в плагин?:

**Comment by halfbrained** [comment]
[Тема - Adwaita](https://gitlab.gnome.org/GNOME/gtk/tree/master/gtk/theme/Adwaita) и [иконки](https://github.com/GNOME/adwaita-icon-theme)

Включить иконки? Там их слишком много, я выбрал все подходящие.

**Comment by Alexey-T** [comment]
включить но как-то не все наверно.

**Comment by halfbrained** [comment]
Я больше уместных иконок не нашел, если вы найдете - и мне нужно добавить - можете дать имена - сделаю
