### ISSUE TITLE
bad work of 'collapse pinned':true

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_tab_icons#11]
before collapse
![Screenshot_2021-03-31_17-47-05](https://user-images.githubusercontent.com/4154978/113163899-469e9d00-9249-11eb-9169-946d3b35602f.png)

pinned all 3 tabs. now it shows only 1 tab collapsed

![Screenshot_2021-03-31_17-47-23](https://user-images.githubusercontent.com/4154978/113163956-5322f580-9249-11eb-9886-375cad2676cb.png)

**Comment by Alexey-T** [comment]
you can see '!' mark in 2nd , 3rd tabs.

**Comment by halfbrained** [comment]
Could you give some more details? Because I am completely unable to reproduce.

Check on fresh install of newest beta.

**Comment by Alexey-T** [comment]
plug config
```
{
  "icon_theme": "vscode_16x16",
  "show_lexer_icons": true,
  "collapse_pinned": true,
  "custom_icons_map": {
    "~/t.txt": "preferences-desktop-font.png",
    "~/tests/t.txt": "emblem-web.png",
    "~/.config/cudatext/settings/cuda_tab_icons.json": "avatar-default.png"
  }
}
```

Cud's config
```
{
  "pylib__linux" : "/usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0",
  "ui_toolbar_show" : true,
    "ui_sidebar_on_right": true,
    "ui_tab_variable_width": true,
}
```

run Cud. no files.
open file which was not opened befiore. e.g. project1.lpi with lexer XML.
Tab title shows XML icon.
call "Pinned' for it.
-->
title shows "!project1.lpi".

**Comment by Alexey-T** [comment]
note!
after I chosen some icon from 'set tab icon..' and THEN pinned--- its collapsed

**Comment by halfbrained** [comment]
I only collapse tabs with custom icon, not filetype-icon.

My thinking here is that you won't be able to differentiate tabs with same filetypes if they are collapsed.

If you were expecting it to work, I should add an option?

**Comment by Alexey-T** [comment]
ahh, OK then.
