### ISSUE TITLE
support subdir in 'data'

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_tab_icons#4]
плохо давать юзеру чтото пихать в папку плагина. оно сотрется при reinstall. дайте ему папку в data/придуматьчтото

**Comment by halfbrained** [comment]
сделал, загружу вместе с 'collapse_pinned'

**Comment by halfbrained** [comment]
вот коммит - https://github.com/halfbrained/cuda_tab_icons/commit/d195e58c24f15f324cfc8baa46519f24b118bdd2

не то issue написал :)
