### ISSUE TITLE
change api= in .inf file because you used EDSTATE_PINNED

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_tab_icons#5]

**Comment by halfbrained** [comment]
Are you sure? I checked, plugin works on older CudaText that is without EDSTATE_PINNED.

I give a message to update CudaText and disable the option that uses new api.

**Comment by Alexey-T** [comment]
that's OK too.

**Comment by Alexey-T** [comment]
that's not done yet.

**Comment by halfbrained** [comment]
How so? 

[Here it is](https://github.com/halfbrained/cuda_tab_icons/commit/d195e58c24f15f324cfc8baa46519f24b118bdd2#diff-8e2c1f727276d30ced72fa67cb848772a9802162bec39b42a8df5359fd063a4cR244-R250)

**Comment by Alexey-T** [comment]
but this will crash-
```
    def on_state_ed(self, ed_self, state):

        if not self.collapse_pinned:
            return # option not enabled

        # display 'modified' character for pinned & collapsed
        if state in [EDSTATE_MODIFIED, EDSTATE_PINNED]:
            if ed_self.get_filename() in self.misc_icon_map: # has custom icon
                self.update_title(ed_self)
```

**Comment by Alexey-T** [comment]
ah, ok.
