### ISSUE TITLE
add some subset of Gnome icons, so I can test the 'icon aliases' ?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_tab_icons#7]

**Comment by halfbrained** [comment]
Sorry for the confusion, I wasn't clear in my explanation.

.png files in plugin's `misc_icons` folder - from GNOME Adwaita theme.

For example icon: misc_icons/changes-prevent.png

name of that file wouldn't be very helpful when you choose an icon to set to a tab, so I show an alias - `lock`:
``` Python
icon_aliases = {
    ...
    'changes-prevent.png': 'lock',
    ...
}
```

This is what aliases are for. Plugin only uses icons from its `misc_icons` directory, and `CudaText/data/tabsicons/`

**Comment by Alexey-T** [comment]
but Github don't have any icons. maybe u didn't uploade em?

**Comment by halfbrained** [comment]
Hahaha, now that makes sense :D

[added](https://github.com/halfbrained/cuda_tab_icons/commit/bb3bef45c61f086f5cb191c55b7099d04f60e3da)
